first version of application-shell-wrapper-template

diff --git a/bash-wrapper-functions b/bash-wrapper-functions
--- a/bash-wrapper-functions
+++ b/bash-wrapper-functions
@@ -10,6 +10,17 @@
 
 bash_wrapper_functions_version=2-SNAPSHOT-2
 
+function error() {
+
+    echo "[error]: "$@ 1>&2
+    exit 1
+}
+
+function debug() {
+
+    ${VERBOSE} && echo $@ 1>&2
+}
+
 #
 # Attempts to identify JAVA_HOME and returns the path to the java binary based on that, while verifying the presence
 # and the executability of the binary. If JAVA_HOME is not found, then the method simply returns "java" with the
@@ -76,8 +87,18 @@ function get-classpath-from-directory() {
         ${first} && first=false || echo -n ":"
         echo -n ${i}
     done
-
 }
 
+#
+# "Light" version retrieval. The function attempts to located the VERSION file. If found, and if carrying a valid
+# content, it is displayed. Otherwise, the calling layer should pass the command to the java runtime.
+#
+# See https://kb.novaordis.com/index.php/Nova_Ordis_Utilities_Version_Metadata_Handling#.22Light.22_Version_Reporting
+#
+function get-version() {
+
+    [ -f $(dirname $0)/../lib/VERSION ] && { cat $(dirname $0)/../lib/VERSION; return 0; }
+    return 1
+}
 
 
